name: BCT.AWK.Converter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Converter
      run: dotnet publish Converter/BCT.AWK.Converter.csproj  -c Release -o release/converter
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
       name: BCT.AWK.Converter_${{github.run_number}}
       path: release/converter
